-- 由 aichat-common/md/convert.sql（Oracle）按 mysql-temp/temp.sql 模板转换为 MySQL（含备注）

CREATE TABLE `PMS_COUNTER_GROUP`  (
  `COUNTERGROUP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '定时组号ID',
  `COUNTERGROUP_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '定时组号编号,自动生成:船舶ID+D+xxx',
  `VESSEL_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '船舶ID',
  `VESSEL_EQUIP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '设备ID',
  `EQUIP_NO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'cwbt码',
  `COUNTERGROUP_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '名称',
  `LAST_UPDATE` datetime NULL DEFAULT NULL COMMENT '最近一次更新日期',
  `TOTAL_VALUE` decimal(12,2) NULL DEFAULT NULL COMMENT '总运行时间VOP_VESSEL_EQUIP .totalRuntime 涉及单独设备计时器的数据 不能更新到这里，这里只更新定时组号的数据。例如主机、副机等',
  `CREATED_BY_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CREATED_BY_USER',
  `CREATED_OFFICE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CREATED_OFFICE',
  `CREATED_DTM_LOC` datetime NULL DEFAULT NULL COMMENT 'CREATED_DTM_LOC',
  `CREATED_TIME_ZONE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CREATED_TIME_ZONE',
  `UPDATED_BY_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UPDATED_BY_USER',
  `UPDATED_OFFICE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UPDATED_OFFICE',
  `UPDATED_DTM_LOC` datetime NULL DEFAULT NULL COMMENT 'UPDATED_DTM_LOC',
  `UPDATED_TIME_ZONE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UPDATED_TIME_ZONE',
  `RECORD_VERSION` decimal(10,0) NULL DEFAULT NULL COMMENT 'RECORD_VERSION',
  `PRINCIPAL_GROUP_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'PRINCIPAL_GROUP_CODE',
  `COMPANY_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'COMPANY_CODE',
  `IS_DELETE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '删除标志',
  `REMARK` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `LAST_NUM` decimal(10,2) NULL DEFAULT NULL COMMENT '上次读数值',
  `COUNTERGROUP_NAME_EN` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '英文名称',
  PRIMARY KEY (`COUNTERGROUP_ID`)
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '存储设备计时器组，对应到航标系统中就是定时组号';
