-- 由 aichat-common/md/PMS_COUNTER_TIMEGROUP.sql（Oracle）按 mysql-temp/temp.sql 模板转换为 MySQL（含备注）

CREATE TABLE `PMS_COUNTER_TIMEGROUP`  (
  `COUNTERTIMEGROUP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'ID',
  `COUNTERTIMEGROUP_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '时间组号编号,自动生成:船舶ID+S+xxx',
  `COUNTERTIMEGROUP_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '时间组号名称',
  `COUNTERGROUP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '定时组号ID',
  `COUNTERGROUP_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '定时组号编号,自动生成:船舶ID+D+xxx',
  `COUNTERGROUP_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '定时组号名称',
  `VESSEL_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '船舶ID',
  `VESSEL_EQUIP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '设备ID',
  `EQUIP_NO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'cwbt码',
  `LAST_UPDATE` datetime NULL DEFAULT NULL COMMENT '最近一次更新日期',
  `TOTAL_VALUE` decimal(10,0) NULL DEFAULT NULL COMMENT '总运行时间',
  `CREATED_BY_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CREATED_BY_USER',
  `CREATED_OFFICE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CREATED_OFFICE',
  `CREATED_DTM_LOC` datetime NULL DEFAULT NULL COMMENT 'CREATED_DTM_LOC',
  `CREATED_TIME_ZONE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'CREATED_TIME_ZONE',
  `UPDATED_BY_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UPDATED_BY_USER',
  `UPDATED_OFFICE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UPDATED_OFFICE',
  `UPDATED_DTM_LOC` datetime NULL DEFAULT NULL COMMENT 'UPDATED_DTM_LOC',
  `UPDATED_TIME_ZONE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'UPDATED_TIME_ZONE',
  `RECORD_VERSION` decimal(10,0) NULL DEFAULT NULL COMMENT 'RECORD_VERSION',
  `PRINCIPAL_GROUP_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'PRINCIPAL_GROUP_CODE',
  `COMPANY_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'COMPANY_CODE',
  `IS_DELETE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '删除标志',
  `REMARK` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`COUNTERTIMEGROUP_ID`)
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '虚拟概念 是介于计时器组和设备计时器之间的一个概念 3）  时间组号：将所有可同时更新的一小组设备计时器聚集起来，关联在计时器组下的团体，成为时间组号。例如：主机是计时器组，主机NO1缸及附属设备的组合起来统称主机NO1缸时间组号';

