-- 由 aichat-common/md/PMS_EQUIP_RUN_TIME_LOG.sql（Oracle）按 mysql-temp/temp.sql 模板转换为 MySQL（含备注）

CREATE TABLE `PMS_EQUIP_RUN_TIME_LOG`  (
  `PMS_EQUIP_RUN_TIME_LOG_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `COMPANY_CODE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `CREATED_BY_USER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `CREATED_DTM_LOC` datetime NULL DEFAULT NULL,
  `CREATED_OFFICE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `CREATED_TIME_ZONE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `PRINCIPAL_GROUP_CODE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `RECORD_VERSION` decimal(10,0) NULL DEFAULT NULL,
  `UPDATED_BY_USER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `UPDATED_DTM_LOC` datetime NULL DEFAULT NULL,
  `UPDATED_OFFICE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `UPDATED_TIME_ZONE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `COUNTER_TOTAL` decimal(19,2) NULL DEFAULT NULL,
  `DEL_FLAG` decimal(19,2) NULL DEFAULT NULL,
  `EQUIP_NO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `INCREASE` decimal(19,2) NULL DEFAULT NULL,
  `READ_DATE` datetime NULL DEFAULT NULL,
  `READ_WAY` decimal(19,2) NULL DEFAULT NULL,
  `REMARK` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `TOTAL_RUNTIME` decimal(19,2) NULL DEFAULT NULL,
  `VESSEL_CODE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `VESSEL_EQUIP_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `IS_DELETE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '删除状态',
  PRIMARY KEY (`PMS_EQUIP_RUN_TIME_LOG_ID`)
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

