create view VW_PMSNEW_WORK_PLAN as
SELECT
 --Distinct -- add by leo on 2022-04-14
T."WORK_PLAN_ID",T."WORK_CONTENT_ID",T."VESSEL_CODE",T."CWBT_CODE",T."DEPT",T."CYCLE_TYPE",T."BEGIN_DATE",T."IS_OVERDUE",T."PLAN_DATE",T."LAST_DATE",T."COMPLETE_DATE",T."RUNTIME_AFTER_OVERHAUL",T."PRINCIPAL",T."COMPLETE_CONTENT",T."WORK_TIPS",T."AUDITOR",T."AUDIT_VIEWS",T."AUDIT_DATE",T."STATUS",T."IS_PROVISIONAL",T."IS_ADJUSTED",T."IS_DELETE",T."COMPANY_CODE",T."REMARK",T."CREATED_BY_USER",T."CREATED_OFFICE",T."CREATED_DTM_LOC",T."CREATED_TIME_ZONE",T."UPDATED_BY_USER",T."UPDATED_OFFICE",T."UPDATED_DTM_LOC",T."UPDATED_TIME_ZONE",T."RECORD_VERSION",T."PRINCIPAL_GROUP_CODE",T."REMAINING_TIME",T."MAINTAIN_GRADE",T."SPAN_LEFT",T."SPAN_RIGHT",T."PERIOD",T."WORK_CONTENT",T."GROUPWORK_TYPE",T."RESPONSIBLE_PERSON",T."VESSEL_AUDITOR",T."VESSEL_AUDIT_VIEWS",T."VESSEL_AUDIT_DATE",T."KT",T."CWBT_CODE_NAME",T."WORK_PLAN_NO",T."VESSEL_EQUIP_ID",
WC.KMRH  AS KMRH,
WC.WORK_CONTENT_NO  AS WORK_CONTENT_NO,
WC.ADVERT_MATTER AS ADVERT_MATTER,
VV.VESSEL_NAME AS VESSEL_NAME,
VV.VESSEL_NAME_EN AS VESSEL_NAME_EN,
CCS.DISPLAY_VALUE_CN AS STATUS_NAME,
CCS.DISPLAY_VALUE AS STATUS_NAME_EN,
CCD.DISPLAY_VALUE_CN AS DEPART_NAME,
CCD.DISPLAY_VALUE AS DEPART_NAME_EN,
CCJ.DISPLAY_VALUE_CN AS RESPONSIBLE_PERSON_NAME,
CCJ.DISPLAY_VALUE AS RESPONSIBLE_PERSON_NAME_EN,
CCC.DISPLAY_VALUE_CN AS CYCLE_TYPE_NAME,
CCC.DISPLAY_VALUE AS CYCLE_TYPE_NAME_EN,
VVE.PMS_CODE AS PMS_CODE,
VVE.IS_PMS AS IS_PMS, --是否PMS
VVE.Equip_Name_En as CWBT_CODE_NAME_EN,
WC.Work_Content_En,
NVL(VVE.IS_PIVOTAL,'0') AS IS_PIVOTAL, --是否关键设备
VVE.FIRE_FLAG AS  FIRE_FLAG,--是否消防救生设备
VVE.IS_ENVIRONMENT AS  IS_ENVIRONMENT, --是否环保设备
VVE.IS_EMERGENCY AS IS_EMERGENCY, -- 是否应急设备
VVE.CCS_CODE  AS CCS_CODE,
(case when trunc(months_between(sysdate,vv.date_of_production)/12)>12 then '1' else '0' end)  as old_vessel,
VV.MMSI as mmsi  -- mmsi接口调用

FROM PMS_WORK_PLAN T

LEFT JOIN PMS_WORK_CONTENT WC ON T.VESSEL_CODE = WC.VESSEL_CODE AND T.WORK_CONTENT_ID = WC.WORK_CONTENT_ID  --改为left join ,因为有临时的工作指令，不关联工作卡
INNER JOIN VOP_VESSEL_EQUIP VVE ON T.VESSEL_CODE = VVE.VESSEL_CODE AND T.VESSEL_EQUIP_ID = VVE.VESSEL_EQUIP_ID
INNER JOIN VOP_VESSEL VV ON T.VESSEL_CODE = VV.VESSEL_CODE  and ( NVL(VV.tetired_flag,'1') = '1'  or t.status=3 )--未退役 1  已退役2  企业微信散运李宝新 提出对于退役船舶的工单，在工作指令的界面里只显示 审核通过(岸基) 状态的工单供查询，其他状态的都屏蔽掉 add by swk 2023年08月16日
INNER JOIN CDM_CODEDICT CCS ON CCS.CODE_TYPE = 'PMS_WORK_PLAN_STATUS' AND T.STATUS = CCS.CODE_VALUE
INNER JOIN CDM_CODEDICT CCD ON CCD.CODE_TYPE = 'PMS_VESSEL_DEPARTMENT' AND T.DEPT = CCD.CODE_VALUE
INNER JOIN CDM_CODEDICT CCJ ON ((CCJ.CODE_TYPE = 'PMS_VESSEL_JOB'  AND T.VESSEL_CODE<>'X099') or (CCJ.CODE_TYPE = 'PMS_YL_VESSEL_JOB_ADD' AND T.VESSEL_CODE='X099'))   AND T.RESPONSIBLE_PERSON= CCJ.CODE_VALUE  --星旅 邮轮船舶职务特殊处理

INNER JOIN CDM_CODEDICT CCC ON CCC.CODE_TYPE = 'PMS_CYCLE_TYPE' AND T.CYCLE_TYPE = CCC.CODE_VALUE

WHERE NVL(T.IS_DELETE,'0') <> '1'
/

